//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCeza
    {
        public int CezaID { get; set; }
        public Nullable<int> CezaUye { get; set; }
        public Nullable<int> CezaHareket { get; set; }
        public Nullable<System.DateTime> CezaBaslangic { get; set; }
        public Nullable<System.DateTime> CezaBitis { get; set; }
        public Nullable<decimal> CezaTutar { get; set; }
    
        public virtual TblHareket TblHareket { get; set; }
        public virtual TblUye TblUye { get; set; }
    }
}
