//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKasa
    {
        public int KasaID { get; set; }
        public string KasaAy { get; set; }
        public Nullable<decimal> KasaTutar { get; set; }
        public string KasaAciklama { get; set; }
    }
}
