//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKategori()
        {
            this.TblKitap = new HashSet<TblKitap>();
        }
    
        public int KategoriID { get; set; }
        public string KategoriAd { get; set; }
        public string KategoriDetay { get; set; }
        public Nullable<bool> KategoriDurum { get; set; }
        public Nullable<System.DateTime> KategoriEklenmeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKitap> TblKitap { get; set; }
    }
}
