//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPersonel()
        {
            this.TblHareket = new HashSet<TblHareket>();
        }
    
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelKullaniciAdi { get; set; }
        public string PersonelParola { get; set; }
        public string PersonelAdres { get; set; }
        public string PersonelTC { get; set; }
        public Nullable<bool> PersonelDurum { get; set; }
        public string PersonelDetay { get; set; }
        public string PersonelGorsel { get; set; }
        public Nullable<System.DateTime> PersonelDogumTarihi { get; set; }
        public Nullable<System.DateTime> PersonelEklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHareket> TblHareket { get; set; }
    }
}
