//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUye()
        {
            this.TblCeza = new HashSet<TblCeza>();
            this.TblHareket = new HashSet<TblHareket>();
        }
    
        public int UyeID { get; set; }
        public string UyeAd { get; set; }
        public string UyeSoyad { get; set; }
        public string UyeMail { get; set; }
        public string UyeTelefon { get; set; }
        public string UyeKullaniciAdi { get; set; }
        public string UyeParola { get; set; }
        public string UyeAdres { get; set; }
        public string UyeTC { get; set; }
        public Nullable<bool> UyeDurum { get; set; }
        public string UyeDetay { get; set; }
        public string UyeGorsel { get; set; }
        public Nullable<System.DateTime> UyeDogumTarihi { get; set; }
        public string UyeMeslegi { get; set; }
        public Nullable<System.DateTime> UyeEklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCeza> TblCeza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHareket> TblHareket { get; set; }
    }
}
